disabled_rules:
  - file_length
  - function_body_length
  - line_length
  - trailing_whitespace
  - type_body_length
  - vertical_whitespace
  - void_return

excluded:
  - Pods
  - Carthage

# This is a strange one, since it also includes init functions
function_parameter_count:
  warning: 8
  error: 8

variable_name:
  excluded:
    - ok
    - vc
